### PR TITLE
update index page

### PR DESCRIPTION
**Pull request by jd-lara**
More documentation updates

### CODE REVIEW

**Comment by kdayday** [comment]
@jd-lara Here are the docstrings needed in `constraints.jl` and `variables.jl`:

- [ ] AncillaryServiceVariableDischarge
- [ ] AncillaryServiceVariableCharge
- [ ] StateofChargeLimitsConstraint
- [ ] StorageCyclingCharge
- [ ] StorageCyclingDischarge
- [ ] ReserveCoverageConstraint
- [ ] ReserveCoverageConstraintEndOfPeriod
- [ ] ReserveCompleteCoverageConstraint
- [ ] ReserveCompleteCoverageConstraintEndOfPeriod
- [ ] StorageTotalReserveConstraint
- [ ] ReserveDischargeConstraint
- [ ] ReserveChargeConstraint 

These constraints are not exported and also don't have docstrings. They don't show up in either the public or internal API. Should they be exported?
- [ ]  StateofChargeTargetConstraint
- [ ] StorageRegularizationConstraintCharge
- [ ] StorageRegularizationConstraintDischarge

**Comment by rodrigomha** [comment]
This PR should try to close #45 
and also #34

**Comment by kdayday** [comment]
> This PR should try to close #45 (if possible) and also #34 (if possible)

Or these could be addressed as part of Anna's re-organization @annacasavant

**Comment by kdayday** [comment]
> @jd-lara Here are the docstrings needed in `constraints.jl` and `variables.jl`:
> 
>     * [ ]  AncillaryServiceVariableDischarge
> 
>     * [ ]  AncillaryServiceVariableCharge
> 
>     * [ ]  StateofChargeLimitsConstraint
> 
>     * [ ]  StorageCyclingCharge
> 
>     * [ ]  StorageCyclingDischarge
> 
>     * [ ]  ReserveCoverageConstraint
> 
>     * [ ]  ReserveCoverageConstraintEndOfPeriod
> 
>     * [ ]  ReserveCompleteCoverageConstraint
> 
>     * [ ]  ReserveCompleteCoverageConstraintEndOfPeriod
> 
>     * [ ]  StorageTotalReserveConstraint
> 
>     * [ ]  ReserveDischargeConstraint
> 
>     * [ ]  ReserveChargeConstraint
> 
> 
> These constraints are not exported and also don't have docstrings. They don't show up in either the public or internal API. Should they be exported?
> 
>     * [ ]   StateofChargeTargetConstraint
> 
>     * [ ]  StorageRegularizationConstraintCharge
> 
>     * [ ]  StorageRegularizationConstraintDischarge

@jd-lara What's the status on getting these docstrings filled out? If you don't have availability, could you share your Latex file with @annacasavant to finish this PR? Thanks!

**Comment by rodrigomha** [comment]
Just rebased with main. Documentation is compiling correctly locally using PowerSimulations main. We need to get a release for PowerSimulations that can use the new version of storage.

**Pull request merged**
